### ISSUE TITLE
How does the "field" meta query work?

### ISSUE THREAD

**Issue by bearline** [fortunejs/fortune-micro-api#3]
I apologize if I am missing something obvious, but I cannot get the "field" query parameter to work. In my case I have a user record type with a name and an age, and I want to show the name only. I have tried writing the query string in all kinds of formats, including "?field[name]" and "?fields[name]", but nothing happens and the meta object just says "µ:meta":{ ... "field":{} }".

I'd be grateful if you could give me an example on how to use the "fields" parameter correctly!

I happened upon another issue while trying to find the correct format for the query string. The following URL gave an unexpected result:

/users?limit=1&sort=-age&fields[age]

When making a GET request to the above URL, the meta object returned this "µ:meta":{ ... "field":{}, "sort":{"age&fields[age]":false} }".

**Comment by bearline** [comment]
I figured it out the correct format: "fields[user]=name". When using this format, the above issue does not apply. The only thing is that the meta "field" definition is always empty, showing just "µ:meta":{ ... "field":{} }". Perhaps this is due to the query parameter being called "fields", but the meta parameter is called "field"? It's just a wild guess though.

**Comment by 0x8890** [comment]
It's definitely a bug that the meta field object is empty, will investigate.

**Comment by 0x8890** [comment]
Fixed in commit https://github.com/fortunejs/fortune-micro-api/commit/fdac50624baf142f0d09b35874432c7446f39b13.
